// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLUC0CvbTSvMNTSTVS_-W23f-1XzJtaM',
    appId: '1:556311763735:web:6a00ee085bd8d2d6fb7552',
    messagingSenderId: '556311763735',
    projectId: 'crudtutorial-ea3a6',
    authDomain: 'crudtutorial-ea3a6.firebaseapp.com',
    storageBucket: 'crudtutorial-ea3a6.firebasestorage.app',
    measurementId: 'G-2SVY82CXPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYU_HTxZ8OR5lmBtdtYUWi5LUp8v6rV1o',
    appId: '1:556311763735:android:3c15f7e36557817dfb7552',
    messagingSenderId: '556311763735',
    projectId: 'crudtutorial-ea3a6',
    storageBucket: 'crudtutorial-ea3a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5AXnqpexMdKl0MbCX8WwJx7RJBIFIkSs',
    appId: '1:556311763735:ios:ce0eb71a502474a4fb7552',
    messagingSenderId: '556311763735',
    projectId: 'crudtutorial-ea3a6',
    storageBucket: 'crudtutorial-ea3a6.firebasestorage.app',
    iosBundleId: 'com.example.crudTutorialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5AXnqpexMdKl0MbCX8WwJx7RJBIFIkSs',
    appId: '1:556311763735:ios:ce0eb71a502474a4fb7552',
    messagingSenderId: '556311763735',
    projectId: 'crudtutorial-ea3a6',
    storageBucket: 'crudtutorial-ea3a6.firebasestorage.app',
    iosBundleId: 'com.example.crudTutorialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLUC0CvbTSvMNTSTVS_-W23f-1XzJtaM',
    appId: '1:556311763735:web:4a147f27581ad724fb7552',
    messagingSenderId: '556311763735',
    projectId: 'crudtutorial-ea3a6',
    authDomain: 'crudtutorial-ea3a6.firebaseapp.com',
    storageBucket: 'crudtutorial-ea3a6.firebasestorage.app',
    measurementId: 'G-MXH3BBGJ86',
  );
}
